const componentsIndex = {
  'resistor': {
    id: 'resistor',
    name: 'Resistor',
    category: 'passive',
    description: 'A passive two-terminal electrical component that implements electrical resistance.',
    tags: ['resistance', 'ohm', 'passive', 'current limiting'],
  },
  'capacitor': {
    id: 'capacitor',
    name: 'Capacitor',
    category: 'passive',
    description: 'A passive two-terminal electronic component that stores electrical energy.',
    tags: ['capacitance', 'farad', 'passive', 'energy storage'],
  },
  'inductor': {
    id: 'inductor',
    name: 'Inductor',
    category: 'passive',
    description: 'An inductor is a passive two-terminal component that stores energy in a magnetic field when current flows through it.',
    tags: ['passive', 'inductor'],
  },
  'transformer': {
    id: 'transformer',
    name: 'Transformer',
    category: 'passive',
    description: 'A passive component that transfers electrical energy between circuits.',
    tags: ['induction', 'voltage', 'power'],
  },
  'potentiometer': {
    id: 'potentiometer',
    name: 'Potentiometer',
    category: 'passive',
    description: 'A potentiometer is a three-terminal variable resistor with a sliding or rotating contact that taps a portion of a resistive element, acting as an adjustable voltage divider.',
    tags: ['passive', 'potentiometer'],
  },
  'varistor': {
    id: 'varistor',
    name: 'Varistor',
    category: 'passive',
    description: 'A varistor is a voltage-dependent resistor whose resistance drops sharply when the applied voltage exceeds a threshold, used primarily for surge and overvoltage protection.',
    tags: ['passive', 'varistor'],
  },
  'thermistor': {
    id: 'thermistor',
    name: 'Thermistor',
    category: 'passive',
    description: 'A thermistor is a temperature-sensitive resistor whose resistance changes significantly with temperature.',
    tags: ['passive', 'thermistor'],
  },
  'rheostat': {
    id: 'rheostat',
    name: 'Rheostat',
    category: 'passive',
    description: 'A rheostat is a two-terminal variable resistor used to control current by inserting a adjustable resistance in series with a load.',
    tags: ['passive', 'rheostat'],
  },
  'trimmer': {
    id: 'trimmer',
    name: 'Trimmer Potentiometer',
    category: 'passive',
    description: 'A trimmer (trimmer potentiometer) is a small, preset variable resistor adjusted occasionally with a screwdriver to calibrate a circuit.',
    tags: ['passive', 'trimmer', 'potentiometer'],
  },
  'wirewound-resistor': {
    id: 'wirewound-resistor',
    name: 'Wirewound Resistor',
    category: 'passive',
    description: 'A wirewound resistor is made by winding a resistive wire (such as nichrome) around an insulating core, providing precise, high-power resistance.',
    tags: ['passive', 'wirewound', 'resistor'],
  },
  'ceramic-resonator': {
    id: 'ceramic-resonator',
    name: 'Ceramic Resonator',
    category: 'passive',
    description: 'A ceramic resonator is a piezoelectric ceramic device that resonates at a fixed frequency, used as a low-cost clock source for microcontrollers.',
    tags: ['passive', 'ceramic', 'resonator'],
  },
  'crystal-oscillator': {
    id: 'crystal-oscillator',
    name: 'Crystal Oscillator',
    category: 'passive',
    description: 'A crystal oscillator uses the mechanical resonance of a piezoelectric quartz crystal to generate a highly stable electrical frequency.',
    tags: ['passive', 'crystal', 'oscillator'],
  },
  'diode': {
    id: 'diode',
    name: 'Diode',
    category: 'semiconductor',
    description: 'A two-terminal electronic component that conducts current primarily in one direction.',
    tags: ['rectifier', 'semiconductor', 'pn-junction'],
  },
  'led': {
    id: 'led',
    name: 'Light Emitting Diode',
    category: 'semiconductor',
    description: 'A light-emitting diode (LED) is a semiconductor diode that emits light when forward biased, through electroluminescence in a direct-bandgap material.',
    tags: ['semiconductor', 'light', 'emitting', 'diode'],
  },
  'zener-diode': {
    id: 'zener-diode',
    name: 'Zener Diode',
    category: 'semiconductor',
    description: 'A Zener diode is a silicon diode designed to operate in reverse breakdown, maintaining a stable reference voltage across a wide current range.',
    tags: ['semiconductor', 'zener', 'diode'],
  },
  'schottky-diode': {
    id: 'schottky-diode',
    name: 'Schottky Diode',
    category: 'semiconductor',
    description: 'A Schottky diode is formed by a metal-semiconductor junction, giving a low forward voltage drop and very fast switching.',
    tags: ['semiconductor', 'schottky', 'diode'],
  },
  'photodiode': {
    id: 'photodiode',
    name: 'Photodiode',
    category: 'semiconductor',
    description: 'A photodiode is a p-n junction that converts light into current when photons generate electron-hole pairs in the depletion region.',
    tags: ['semiconductor', 'photodiode'],
  },
  'transistor': {
    id: 'transistor',
    name: 'Bipolar Transistor',
    category: 'semiconductor',
    description: 'A semiconductor device used to amplify or switch electronic signals.',
    tags: ['amplifier', 'switch', 'BJT', 'semiconductor'],
  },
  'mosfet': {
    id: 'mosfet',
    name: 'MOSFET',
    category: 'semiconductor',
    description: 'A field-effect transistor used for switching and amplifying electronic signals.',
    tags: ['fet', 'field-effect', 'switch', 'semiconductor'],
  },
  'jfet': {
    id: 'jfet',
    name: 'JFET',
    category: 'semiconductor',
    description: 'A JFET (junction field-effect transistor) is a voltage-controlled device where a reverse-biased p-n junction gate depletes a channel to control current.',
    tags: ['semiconductor', 'jfet'],
  },
  'igbt': {
    id: 'igbt',
    name: 'IGBT',
    category: 'semiconductor',
    description: 'An IGBT (insulated-gate bipolar transistor) combines a MOSFET input with a bipolar output, giving high-voltage, high-current switching with low on-state loss.',
    tags: ['semiconductor', 'igbt'],
  },
  'thyristor': {
    id: 'thyristor',
    name: 'Thyristor (SCR)',
    category: 'semiconductor',
    description: 'A thyristor (SCR) is a four-layer p-n-p-n semiconductor device that acts as a latching switch, conducting only after a gate trigger and continuing until current falls below hold.',
    tags: ['semiconductor', 'thyristor', 'scr'],
  },
  'triac': {
    id: 'triac',
    name: 'TRIAC',
    category: 'semiconductor',
    description: 'A TRIAC is a bidirectional thyristor that conducts in both directions when triggered by a gate pulse, used for AC power control.',
    tags: ['semiconductor', 'triac'],
  },
  'diac': {
    id: 'diac',
    name: 'DIAC',
    category: 'semiconductor',
    description: 'A DIAC is a bidirectional trigger diode that conducts abruptly when its breakover voltage is exceeded in either direction, used to trigger TRIACs.',
    tags: ['semiconductor', 'diac'],
  },
  'phototransistor': {
    id: 'phototransistor',
    name: 'Phototransistor',
    category: 'semiconductor',
    description: 'A phototransistor is a bipolar transistor whose base current is generated by incident light, producing a larger collector current gain than a photodiode.',
    tags: ['semiconductor', 'phototransistor'],
  },
  'ujt': {
    id: 'ujt',
    name: 'Unijunction Transistor',
    category: 'semiconductor',
    description: 'A UJT (unijunction transistor) is a three-terminal device with one emitter and two bases, used mainly as a relaxation oscillator and trigger.',
    tags: ['semiconductor', 'unijunction', 'transistor'],
  },
  'tunnel-diode': {
    id: 'tunnel-diode',
    name: 'Tunnel Diode',
    category: 'semiconductor',
    description: 'A tunnel diode (Esaki diode) is a heavily doped p-n junction exhibiting negative resistance due to quantum tunneling, enabling very high-frequency oscillators.',
    tags: ['semiconductor', 'tunnel', 'diode'],
  },
  'varactor-diode': {
    id: 'varactor-diode',
    name: 'Varactor Diode',
    category: 'semiconductor',
    description: 'A varactor (varicap) diode is a reverse-biased p-n junction whose depletion capacitance varies with applied voltage, acting as a voltage-controlled capacitor.',
    tags: ['semiconductor', 'varactor', 'diode'],
  },
  'voltage-regulator': {
    id: 'voltage-regulator',
    name: 'Voltage Regulator',
    category: 'power-electronics',
    description: 'A voltage regulator maintains a constant output voltage despite variations in input voltage and load current, using linear or switching techniques.',
    tags: ['power-electronics', 'voltage', 'regulator'],
  },
  'dc-power-supply': {
    id: 'dc-power-supply',
    name: 'DC Power Supply',
    category: 'power-electronics',
    description: 'A DC power supply converts AC (or another DC) into a stable direct-current output, typically via rectification, filtering, and regulation.',
    tags: ['power-electronics', 'power', 'supply'],
  },
  'ac-power-supply': {
    id: 'ac-power-supply',
    name: 'AC Power Supply',
    category: 'power-electronics',
    description: 'An AC power supply provides a controllable alternating-voltage output, either from the mains (via transformer) or synthesized by an inverter/function generator.',
    tags: ['power-electronics', 'power', 'supply'],
  },
  'relay': {
    id: 'relay',
    name: 'Relay',
    category: 'electromechanical',
    description: 'An electrically operated switch that uses an electromagnet.',
    tags: ['switch', 'electromagnet', 'electromechanical'],
  },
  'dc-motor': {
    id: 'dc-motor',
    name: 'DC Motor',
    category: 'electromechanical',
    description: 'A DC motor converts electrical DC energy into rotational mechanical energy using magnetic fields and commutation.',
    tags: ['electromechanical', 'motor'],
  },
  'stepper-motor': {
    id: 'stepper-motor',
    name: 'Stepper Motor',
    category: 'electromechanical',
    description: 'A stepper motor rotates in discrete steps, positioning precisely by energizing stator coils in sequence under electronic control.',
    tags: ['electromechanical', 'stepper', 'motor'],
  },
  'servo-motor': {
    id: 'servo-motor',
    name: 'Servo Motor',
    category: 'electromechanical',
    description: 'A servo motor is a motor with integrated feedback (encoder/resolver) and control, providing precise position, speed, or torque.',
    tags: ['electromechanical', 'servo', 'motor'],
  },
  'speaker': {
    id: 'speaker',
    name: 'Loudspeaker',
    category: 'electromechanical',
    description: 'A loudspeaker converts electrical audio signals into sound by driving a diaphragm with a voice coil in a magnetic field.',
    tags: ['electromechanical', 'loudspeaker'],
  },
  'buzzer': {
    id: 'buzzer',
    name: 'Buzzer',
    category: 'electromechanical',
    description: 'A buzzer is an audible signaling device that produces a tone from an electrical signal, using electromagnetic or piezoelectric actuation.',
    tags: ['electromechanical', 'buzzer'],
  },
  'solenoid': {
    id: 'solenoid',
    name: 'Solenoid',
    category: 'electromechanical',
    description: 'A solenoid is a coil that produces a linear (or rotary) mechanical motion when energized, often pushing a plunger into a magnetic field.',
    tags: ['electromechanical', 'solenoid'],
  },
  'contactor': {
    id: 'contactor',
    name: 'Contactor',
    category: 'electromechanical',
    description: 'A contactor is a heavy-duty relay designed to switch large electrical loads, especially high-current AC motors and power circuits.',
    tags: ['electromechanical', 'contactor'],
  },
  'switch': {
    id: 'switch',
    name: 'Switch',
    category: 'electromechanical',
    description: 'A switch is a mechanical device that opens or closes an electrical circuit, interrupting or diverting current flow.',
    tags: ['electromechanical', 'switch'],
  },
  'push-button': {
    id: 'push-button',
    name: 'Push Button',
    category: 'electromechanical',
    description: 'A push-button is a momentary switch actuated by pressing a button, returning to rest when released (or latching).',
    tags: ['electromechanical', 'push', 'button'],
  },
  'electromagnet': {
    id: 'electromagnet',
    name: 'Electromagnet',
    category: 'electromechanical',
    description: 'An electromagnet is a coil of wire that produces a magnetic field when current flows, controllable by electricity.',
    tags: ['electromechanical', 'electromagnet'],
  },
  'fuse': {
    id: 'fuse',
    name: 'Fuse',
    category: 'protection',
    description: 'A fuse is a sacrificial overcurrent protection device: a metal link that melts and opens the circuit when current exceeds a rated value.',
    tags: ['protection', 'fuse'],
  },
  'circuit-breaker': {
    id: 'circuit-breaker',
    name: 'Circuit Breaker',
    category: 'protection',
    description: 'A circuit breaker is an automatically operated electrical switch that protects a circuit from overcurrent and can be reset.',
    tags: ['protection', 'circuit', 'breaker'],
  },
  'temperature-sensor': {
    id: 'temperature-sensor',
    name: 'Temperature Sensor',
    category: 'sensors',
    description: 'A temperature sensor converts temperature into an electrical signal (resistance, voltage, or digital value).',
    tags: ['sensors', 'temperature', 'sensor'],
  },
  'pressure-sensor': {
    id: 'pressure-sensor',
    name: 'Pressure Sensor',
    category: 'sensors',
    description: 'A pressure sensor measures pressure (force per area) and converts it to an electrical signal.',
    tags: ['sensors', 'pressure', 'sensor'],
  },
  'ultrasonic-sensor': {
    id: 'ultrasonic-sensor',
    name: 'Ultrasonic Sensor',
    category: 'sensors',
    description: 'An ultrasonic sensor measures distance by emitting ultrasound and timing the echo return.',
    tags: ['sensors', 'ultrasonic', 'sensor'],
  },
  'accelerometer': {
    id: 'accelerometer',
    name: 'Accelerometer',
    category: 'sensors',
    description: 'An accelerometer measures proper acceleration (including gravity) along one or more axes.',
    tags: ['sensors', 'accelerometer'],
  },
  'gyroscope': {
    id: 'gyroscope',
    name: 'Gyroscope',
    category: 'sensors',
    description: 'A gyroscope measures angular velocity (rotation rate) about one or more axes.',
    tags: ['sensors', 'gyroscope'],
  },
  'ldr': {
    id: 'ldr',
    name: 'Light Dependent Resistor',
    category: 'sensors',
    description: 'An LDR (light-dependent resistor or photoresistor) changes resistance with incident light intensity.',
    tags: ['sensors', 'light', 'dependent', 'resistor'],
  },
  'proximity-sensor': {
    id: 'proximity-sensor',
    name: 'Proximity Sensor',
    category: 'sensors',
    description: 'A proximity sensor detects the presence of an object without physical contact.',
    tags: ['sensors', 'proximity', 'sensor'],
  },
  'humidity-sensor': {
    id: 'humidity-sensor',
    name: 'Humidity Sensor',
    category: 'sensors',
    description: 'A humidity sensor measures the amount of water vapor in air (relative or absolute humidity).',
    tags: ['sensors', 'humidity', 'sensor'],
  },
  'gas-sensor': {
    id: 'gas-sensor',
    name: 'Gas Sensor',
    category: 'sensors',
    description: 'A gas sensor detects the presence and concentration of gases (e.g., CO, methane, VOC).',
    tags: ['sensors', 'gas', 'sensor'],
  },
  'ir-sensor': {
    id: 'ir-sensor',
    name: 'IR Sensor',
    category: 'sensors',
    description: 'An IR sensor detects infrared radiation, either as a proximity/obstacle detector or as a thermal/remote receiver.',
    tags: ['sensors', 'sensor'],
  },
  'hall-sensor': {
    id: 'hall-sensor',
    name: 'Hall Effect Sensor',
    category: 'sensors',
    description: 'A Hall-effect sensor detects magnetic fields and is used for proximity, position, and current sensing.',
    tags: ['sensors', 'hall', 'effect', 'sensor'],
  },
  'flex-sensor': {
    id: 'flex-sensor',
    name: 'Flex Sensor',
    category: 'sensors',
    description: 'A flex (bend) sensor changes resistance as it is bent, measuring the degree of deflection.',
    tags: ['sensors', 'flex', 'sensor'],
  },
  'touch-sensor': {
    id: 'touch-sensor',
    name: 'Touch Sensor',
    category: 'sensors',
    description: 'A touch sensor detects physical contact or proximity of a finger, enabling intuitive input.',
    tags: ['sensors', 'touch', 'sensor'],
  },
  'op-amp': {
    id: 'op-amp',
    name: 'Operational Amplifier',
    category: 'integrated-circuits',
    description: 'An operational amplifier is a high-gain DC-coupled differential amplifier used for analog signal conditioning.',
    tags: ['integrated-circuits', 'operational', 'amplifier'],
  },
  '555-timer': {
    id: '555-timer',
    name: '555 Timer',
    category: 'integrated-circuits',
    description: 'The 555 timer is a versatile IC for generating pulses, delays, and oscillations.',
    tags: ['integrated-circuits', '555', 'timer'],
  },
  'adc': {
    id: 'adc',
    name: 'Analog to Digital Converter',
    category: 'integrated-circuits',
    description: 'An Analog-to-Digital Converter (ADC) converts continuous analog voltage into digital numbers.',
    tags: ['integrated-circuits', 'analog', 'digital', 'converter'],
  },
  'dac': {
    id: 'dac',
    name: 'Digital to Analog Converter',
    category: 'integrated-circuits',
    description: 'A Digital-to-Analog Converter (DAC) converts digital codes into proportional analog voltages or currents.',
    tags: ['integrated-circuits', 'digital', 'analog', 'converter'],
  },
  'comparator': {
    id: 'comparator',
    name: 'Comparator',
    category: 'integrated-circuits',
    description: 'A comparator compares two voltages and outputs high or low depending on which is greater.',
    tags: ['integrated-circuits', 'comparator'],
  },
  'ldo-regulator': {
    id: 'ldo-regulator',
    name: 'LDO Voltage Regulator',
    category: 'integrated-circuits',
    description: 'A Low-Dropout (LDO) regulator provides a stable output voltage with very small difference between input and output.',
    tags: ['integrated-circuits', 'ldo', 'voltage', 'regulator'],
  },
  'microcontroller': {
    id: 'microcontroller',
    name: 'Microcontroller',
    category: 'integrated-circuits',
    description: 'A microcontroller (MCU) is a self-contained computer on a chip with CPU, memory, and peripherals for embedded control.',
    tags: ['integrated-circuits', 'microcontroller'],
  },
  'fpga': {
    id: 'fpga',
    name: 'FPGA',
    category: 'integrated-circuits',
    description: 'An FPGA (Field-Programmable Gate Array) is a reconfigurable chip of logic blocks and interconnects programmed by the user.',
    tags: ['integrated-circuits', 'fpga'],
  },
  'logic-gate-ic': {
    id: 'logic-gate-ic',
    name: 'Logic Gate IC',
    category: 'integrated-circuits',
    description: 'A logic-gate IC integrates several basic logic gates (AND, OR, NOT, etc.) in one package.',
    tags: ['integrated-circuits', 'logic', 'gate'],
  },
  'audio-amplifier-ic': {
    id: 'audio-amplifier-ic',
    name: 'Audio Amplifier IC',
    category: 'integrated-circuits',
    description: 'An audio power amplifier IC boosts low-level audio signals to drive speakers or headphones.',
    tags: ['integrated-circuits', 'audio', 'amplifier'],
  },
  'motor-driver-ic': {
    id: 'motor-driver-ic',
    name: 'Motor Driver IC',
    category: 'integrated-circuits',
    description: 'A motor driver IC controls the direction and speed of a motor, typically using an H-bridge.',
    tags: ['integrated-circuits', 'motor', 'driver'],
  },
  'logic-gates': {
    id: 'logic-gates',
    name: 'Logic Gates',
    category: 'digital',
    description: 'Logic gates are the fundamental building blocks of digital circuits that implement Boolean functions.',
    tags: ['digital', 'logic', 'gates'],
  },
  'flip-flop': {
    id: 'flip-flop',
    name: 'Flip-Flop',
    category: 'digital',
    description: 'A flip-flop is a bistable sequential circuit that stores one bit of state, changing on a clock or control edge.',
    tags: ['digital', 'flip', 'flop'],
  },
  'counter': {
    id: 'counter',
    name: 'Counter',
    category: 'digital',
    description: 'A counter is a sequential circuit that counts clock pulses, producing a binary (or other) sequence.',
    tags: ['digital', 'counter'],
  },
  'register': {
    id: 'register',
    name: 'Register',
    category: 'digital',
    description: 'A register is a group of flip-flops that stores multiple bits, often with parallel load/shift capability.',
    tags: ['digital', 'register'],
  },
  'multiplexer': {
    id: 'multiplexer',
    name: 'Multiplexer',
    category: 'digital',
    description: 'A multiplexer (MUX) selects one of many inputs and routes it to a single output based on a select code.',
    tags: ['digital', 'multiplexer'],
  },
  'demultiplexer': {
    id: 'demultiplexer',
    name: 'Demultiplexer',
    category: 'digital',
    description: 'A demultiplexer (DEMUX) takes one input and routes it to one of many outputs based on a select code.',
    tags: ['digital', 'demultiplexer'],
  },
  'encoder': {
    id: 'encoder',
    name: 'Encoder',
    category: 'digital',
    description: 'An encoder converts one active input (or a position) into a binary code on its outputs.',
    tags: ['digital', 'encoder'],
  },
  'decoder': {
    id: 'decoder',
    name: 'Decoder',
    category: 'digital',
    description: 'A decoder converts a binary code on its inputs into one active output line among many.',
    tags: ['digital', 'decoder'],
  },
  'lcd': {
    id: 'lcd',
    name: 'Liquid Crystal Display',
    category: 'displays',
    description: 'A Liquid Crystal Display (LCD) uses polarized light and liquid crystals to show images without emitting light itself.',
    tags: ['displays', 'liquid', 'crystal', 'display'],
  },
  'oled': {
    id: 'oled',
    name: 'OLED Display',
    category: 'displays',
    description: 'An OLED (Organic LED) display uses organic compounds that emit light when current flows, pixel by pixel.',
    tags: ['displays', 'oled', 'display'],
  },
  '7-segment': {
    id: '7-segment',
    name: 'Seven Segment Display',
    category: 'displays',
    description: 'A seven-segment display shows decimal digits using seven LED (or LCD) segments arranged as an \'8\'.',
    tags: ['displays', 'seven', 'segment', 'display'],
  },
  'led-matrix': {
    id: 'led-matrix',
    name: 'LED Matrix',
    category: 'displays',
    description: 'An LED matrix arranges LEDs in a grid (rows/columns) to display text, icons, or video.',
    tags: ['displays', 'led', 'matrix'],
  },
  'breadboard': {
    id: 'breadboard',
    name: 'Breadboard',
    category: 'prototyping',
    description: 'A breadboard is a reusable solderless board with spring clips for quickly prototyping circuits.',
    tags: ['prototyping', 'breadboard'],
  },
  'pcb': {
    id: 'pcb',
    name: 'Printed Circuit Board',
    category: 'prototyping',
    description: 'A Printed Circuit Board (PCB) mechanically supports and electrically connects components via copper traces.',
    tags: ['prototyping', 'printed', 'circuit', 'board'],
  },
  'jumper-wire': {
    id: 'jumper-wire',
    name: 'Jumper Wire',
    category: 'prototyping',
    description: 'A jumper wire is a short pre-stripped wire used to make connections on breadboards or between headers.',
    tags: ['prototyping', 'jumper', 'wire'],
  },
  'connector': {
    id: 'connector',
    name: 'Connector',
    category: 'prototyping',
    description: 'A connector is a detachable interface that joins circuits, cables, or boards electrically and mechanically.',
    tags: ['prototyping', 'connector'],
  },
  'antenna': {
    id: 'antenna',
    name: 'Antenna',
    category: 'communication',
    description: 'An antenna is a transducer that converts electrical signals to electromagnetic waves (and vice versa) for radio communication.',
    tags: ['communication', 'antenna'],
  },
  'battery': {
    id: 'battery',
    name: 'Battery',
    category: 'energy-storage',
    description: 'A device that stores chemical energy and converts it to electrical energy.',
    tags: ['power', 'dc', 'energy storage', 'electrochemical'],
  },
}

export default componentsIndex
